[package]
name = "pi-auto-feeder"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
color-eyre = "0.6.5"
futures-util = "0.3.32"
leptos = { version = "0.8.20", features = ["ssr"] }
rppal = "0.22.1"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"] }
